# Configurazione del progetto
[app]
name = "hub"
identifier = "cloud.colosso.app"
key = "{{ SECRET_KEY }}"
version = "0.0.1"
readme = "README.md"
requires-python = ">=3.8"

# Configurazione della messaggistica
[amessage.log]
adapter = "console"
file = ""
level = "debug"
format = "%(asctime)s | %(levelname)-8s | %(process)d | %(message)s"

[amessage.client]
adapter = "websocket"
url = "ws://localhost:8000/messenger"

[amessage.server]
adapter = "websocket"
url = "wss://app.colosso.cloud/messenger"

[message.chatbot]
adapter = "api"
domain = "assistant,chat"
url = "https://openrouter.ai/api/v1/chat/completions"
authorization = "Bearer"
accept = "application/json"
token = "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"

[amessage.backend]
adapter = "redis"
host = "redis-18721.c339.eu-west-3-1.ec2.redns.redis-cloud.com"
port = "18721"
database = "Projects-free-db"
username = "default"
password = ""

# Configurazione della presentazione
[presentation.web]
adapter = "wasm"
host = "0.0.0.0"
port = "8000"
view = "src/domain/view/layout/page.xml"
routes = "src/application/route/app.xml"
#ssl_keyfile = "key.pem"
#ssl_certfile = "cert.pem"

# Configurazione dell'autenticazione
[authentication.supabase]
adapter = "supabase"
url = "https://ljeowpqmovaavxghpsne.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqZW93cHFtb3ZhYXZ4Z2hwc25lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNDI3NDEsImV4cCI6MjA1NjkxODc0MX0.IAIJo8-x2WIa9tk7HQwLxgmAX1JTX0aK3kLTb7FQTG8"

[authentication.github]
adapter = "oauth"
url = "https://github.com/login/oauth/access_token?client_id={{ GITHUB_OAUTH_ID }}&client_secret={{ GITHUB_OAUTH_SECRET }}"
link = "https://github.com/login/oauth/authorize?client_id=Ov23lidpWleO0KCHQVm0&scope=repo,user&state=xyz987"
id = "{{ GITHUB_OAUTH_ID }}"
secret = "{{ GITHUB_OAUTH_SECRET }}"

# Configurazione della persistenza
[persistence.bot]
adapter = "jwt"
url = "https://api.github.com"
app_id = "{{ GITHUB_COLOSSO_ID }}"
installation_id = "{{ GITHUB_COLOSSO_APP }}"
key = "public/colosso-cloud.2024-11-24.private-key.pem"
autologin = "true"

[apersistence.backend]
adapter = "redis"
host = "redis-18721.c339.eu-west-3-1.ec2.redns.redis-cloud.com"
port = "18721"
database = "Projects-free-db"
username = "default"
password = ""

[persistence.supabase]
adapter = "supabase"
url = "https://ljeowpqmovaavxghpsne.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqZW93cHFtb3ZhYXZ4Z2hwc25lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNDI3NDEsImV4cCI6MjA1NjkxODc0MX0.IAIJo8-x2WIa9tk7HQwLxgmAX1JTX0aK3kLTb7FQTG8"
token = "{{ session_token_supabase or 'none' }}"

[persistence.github]
adapter = "api"
url = "https://api.github.com"
authorization = "Bearer "
accept = "application/vnd.github+json"
token = "{% if session.github and session.github.access_token %}{{ session.github.access_token }}{% else %}none{% endif %}"

[persistence.workspace]
adapter = "fs"

# Configurazione dell'automazione
[actuator.devops]
adapter = "ansible"
playbook_path = ""
extra_vars = ""
inventory_file = ""
timeout = ""